' Copyright (c) 2026 Bruce A Henderson
' All rights reserved.
'
' Permission is hereby granted, free of charge, to any person obtaining a copy
' of this software and associated documentation files (the "Software"), to deal
' in the Software without restriction, including without limitation the rights
' to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
' copies of the Software, and to permit persons to whom the Software is
' furnished to do so, subject to the following conditions:
' 
' The above copyright notice and this permission notice shall be included in
' all copies or substantial portions of the Software.
' 
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
' IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
' FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
' AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
' LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
' OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
' THE SOFTWARE.
'
SuperStrict

Module Database.OrmPostgreSql

ModuleInfo "Version: 1.00"
ModuleInfo "License: MIT"
ModuleInfo "Copyright: Bruce A Henderson"

ModuleInfo "History: 1.00"
ModuleInfo "History: Initial Release."

Import Database.Orm
Import Database.PostgreSql

Type TOrmPostgresDialect Extends TOrmDialect

	Method QuoteIdentifier:String(name:String)
		Return "~q" + name.Replace("~q", "~q~q") + "~q"
	End Method

	Method SqlTypeForField:String(fld:TOrmField)
		If fld.isJson Then
			Return "JSONB"
		End If

		If fld.isBool Then
			Return "BOOLEAN"
		End If

		If fld.isEnum Then
			If fld.isEnumString Then
				Return "TEXT"
			End If
			' fallthrough to numeric type...
		End If

		Local ty:TTypeId = fld.typeField.TypeId()
		If ty = ByteTypeId Then
			Return "SMALLINT"
		End If
			
		If ty = ShortTypeId Or ty = IntTypeId Then
			Return "INTEGER"
		End If

		If ty = LongTypeId Or ty = LongIntTypeId Or ty = UIntTypeId Then
			Return "BIGINT"
		End If

		If ty = SizeTTypeId Or ty = ULongTypeId Or ty = ULongIntTypeId Then
			Return "DECIMAL(20,0)"
		End If

		If ty = FloatTypeId Then
			Return "REAL"
		End If

		If ty = DoubleTypeId Then
			Return "DOUBLE PRECISION"
		End If

		If ty = StringTypeId Then
			Return "TEXT"
		End If

		Return "TEXT"
	End Method

	Method AutoGeneratedPrimaryKeyType:String(fld:TOrmField)
		Return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
	End Method

	Method Placeholder:String(index:Int)
		Return "$" + index
	End Method

	Method AddBool(query:TDatabaseQuery, value:Int) Override
		If value Then
			query.AddInt(1)
		Else
			query.AddInt(0)
		End If
	End Method

	Method BoolFromDatabase:Int(value:TDBType)
		If Not value Or value.IsNull() Then
			Return False
		End If

		Return value.GetInt()
	End Method

	Method AddByte(query:TDatabaseQuery, value:Byte) Override
		query.AddInt(value)
	End Method

	Method AddShort(query:TDatabaseQuery, value:Short) Override
		query.AddInt(value)
	End Method

	Method AddUInt(query:TDatabaseQuery, value:UInt) Override
		query.AddLong(Long(value))
	End Method

	Method AddULong(query:TDatabaseQuery, value:ULong) Override
		query.AddString(String.FromULong(value))
	End Method

	Method AddDecimal(query:TDatabaseQuery, value:TDecimal) Override
		If value Then
			query.AddString(value.ToString())
		Else
			query.AddNull()
		End If
	End Method

	Method ByteFromDatabase:Byte(value:TDBType) Override
		Return value.GetByte()
	End Method

	Method ShortFromDatabase:Short(value:TDBType) Override
		Return value.GetShort()
	End Method
	
	Method UIntFromDatabase:UInt(value:TDBType) Override
		Return value.GetUInt()
	End Method

	Method ULongFromDatabase:ULong(value:TDBType) Override
		Return value.GetULong()
	End Method

	Method DecimalFromDatabase:TDecimal(value:TDBType) Override
		Return value.GetDecimal()
	End Method

	Method AddBindValue(query:TDatabaseQuery, value:TDBType) Override
		If value.IsNull() Then
			query.AddNull()
			Return
		End If

		Local ty:Int = value.Kind()
		Select ty
			Case DBTYPE_BOOL
				AddBool(query, value.GetInt())
			Case DBTYPE_BYTE
				AddByte(query, value.GetByte())
			Case DBTYPE_SHORT
				AddShort(query, value.GetShort())
			Case DBTYPE_INT
				query.AddInt(value.GetInt())
			Case DBTYPE_LONG
				query.AddLong(value.GetLong())
			Case DBTYPE_UINT
				AddUInt(query, value.GetUInt())
			Case DBTYPE_ULONG
				AddULong(query, value.GetULong())
			Case DBTYPE_FLOAT
				query.AddFloat(value.GetFloat())
			Case DBTYPE_DOUBLE
				query.AddDouble(value.GetDouble())
			Case DBTYPE_DECIMAL
				AddDecimal(query, value.GetDecimal())
			Case DBTYPE_STRING
				query.AddString(value.GetString())
			Default
				query.AddString(value.ToString())
		End Select
	End Method

	Method GetName:String()
		Return "POSTGRESQL"
	End Method

	Method RewritePlaceholders:String(sql:String)
		Local out:TStringBuilder = New TStringBuilder
		Local index:Int = 1

		Local inSingleQuote:Int
		Local inDoubleQuote:Int

		For Local i:Int = 0 Until sql.Length

			Local ch:Int = sql[i]

			If ch = Asc("'") And Not inDoubleQuote Then
				inSingleQuote = Not inSingleQuote
				out.AppendChar(ch)
				Continue
			End If

			If ch = Asc("~q") And Not inSingleQuote Then
				inDoubleQuote = Not inDoubleQuote
				out.AppendChar(ch)
				Continue
			End If

			If ch = Asc("?") And Not inSingleQuote And Not inDoubleQuote Then

				If i < sql.Length - 1 And sql[i + 1] = Asc("?") Then
					out.Append("?")
					i :+ 1
				Else
					out.Append("$")
					out.Append(index)
					index :+ 1
				End If

				Continue
			End If

			out.AppendChar(ch)
		Next

		Return out.ToString()
	End Method

	Method InsertReturningClause:String(model:TOrmModel)
		If model.primaryKey And model.primaryKey.isAuto Then
			Return " RETURNING " + QuoteIdentifier(model.primaryKey.name)
		End If
		Return ""
	End Method

	Method ReadGeneratedId:Long(query:TDatabaseQuery)
		If query.NextRow() Then
			Return query.Value(0).GetLong()
		End If
		Throw New TOrmException("Insert did not return generated id")
	End Method

End Type

New TOrmPostgresDialect()
